### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by rasuru** [lukazko/4IZ268-Static-website#19]
Checkout my fork

![image](https://user-images.githubusercontent.com/39127725/47618641-a08e5c00-daff-11e8-92d6-d5f4c1901c8d.png)

![image](https://user-images.githubusercontent.com/39127725/47618649-b4d25900-daff-11e8-8acc-8eb3b908afa3.png)

![image](https://user-images.githubusercontent.com/39127725/47618656-bd2a9400-daff-11e8-8a0b-6f72ff67ec16.png)

![image](https://user-images.githubusercontent.com/39127725/47618661-c87dbf80-daff-11e8-8676-8ee392125cd6.png)

![image](https://user-images.githubusercontent.com/39127725/47618663-cfa4cd80-daff-11e8-9d17-5b96aae63f24.png)

**Comment by lukazko** [comment]
Looks really cool!

**Comment by rasuru** [comment]
Thank you! I redesigned the code inside too. You can change the colors to what you like. They do not really matter. Just wanted to bring a little bit of BEM to your project.

Feel free to use my code :)
